apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      timeout: 30s
      derivedFields:
        - name: "event_id"
          matcherRegex: '"event_id":"([^"]+)"'
          url: "http://localhost:3030/explore?orgId=1&left={\"datasource\":\"Loki\",\"queries\":[{\"refId\":\"A\",\"expr\":\"{event_id=\\\"${__value.raw}\\\"}\"}],\"range\":{\"from\":\"now-1h\",\"to\":\"now\"}}"
          urlDisplayLabel: "Buscar Event ID"
    version: 1
    editable: true
    